export const ADD_CONSTRUCTOR_ITEM = 'ADD_CONSTRUCTOR_ITEM';
export const REMOVE_CONSTRUCTOR_ITEM = 'REMOVE_CONSTRUCTOR_ITEM';
export const SORT_CONSTRUCTOR_ITEM = 'SORT_CONSTRUCTOR_ITEM';
export const CLEAR_CONSTRUCTOR_ITEMS = 'CLEAR_CONSTRUCTOR_ITEMS';


